// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Imprint renders the operator-disclosure page required by §5 TMG and
// §18 (2) MStV for German-operated sites. Mirrors the structure of
// blitsbom.eu/imprint — same operator, adapted text for blittermib.
func Imprint() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<article class=\"legal-page\"><h1>Imprint</h1><p>Information disclosed per § 5 of the German Telemediengesetz (TMG) and § 18 (2) of the Medienstaatsvertrag (MStV).</p><h2 id=\"operator\">Operator</h2><address>Ronny Trommer<br>Steinsfelder Weg 22<br>74199 Untergruppenbach<br>Germany</address><h2 id=\"contact\">Contact</h2><ul><li>Email: <a href=\"mailto:hostmaster@no42.org\">hostmaster@no42.org</a></li><li>Phone: +49 (0) 07130 5319759</li><li>GitHub: <a href=\"https://github.com/indigo423\" target=\"_blank\" rel=\"noopener noreferrer\">Ronny Trommer</a></li></ul><h2 id=\"editorial-responsibility\">Editorial responsibility (§ 18 (2) MStV)</h2><p>Responsible for the editorial content of this site is the operator named above.</p><h2 id=\"about-this-site\">About this site</h2><p><code>blittermib</code> is a self-hostable, browser-based reference tool for SNMP MIB files. The project is non-commercial. Source code is available on <a href=\"https://github.com/no42-org/blittermib\" target=\"_blank\" rel=\"noopener noreferrer\">GitHub</a> and licensed under the <a href=\"https://github.com/no42-org/blittermib/blob/main/LICENSE\" target=\"_blank\" rel=\"noopener noreferrer\">MIT License</a>.</p><h2 id=\"liability-for-linked-content\">Liability for linked content</h2><p>External links on this site are provided as a convenience. The operator assumes no responsibility for the content of external sites. If you become aware of unlawful content linked from this site, please contact the email address above; the link will be reviewed and removed where appropriate.</p><h2 id=\"data-processing\">Data processing</h2><p>The <a href=\"/privacy\">privacy notice</a> describes how visitor connection data is handled when this instance is deployed on a public host.</p></article>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("Imprint — blittermib").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
