// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/no42-org/blittermib/internal/model"

// modulePicker is the body-mounted Alpine overlay triggered by
// clicking the module name in the status bar. The full module list
// is preloaded server-side as a hidden JSON payload (it's bounded —
// at most ~1k rows in the worst standard-MIB-bundle case), and
// Alpine renders only the first 10 matches client-side with a
// "+N more" indicator nudging the user to keep typing.
//
// The picker is a centered card overlaying the page (not a
// dropdown anchored to the status-bar button). At 1k modules the
// dropdown would be cramped and a centered overlay reads better
// next to the keyboard-driven type-ahead UX.
func modulePicker(modules []model.Module) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"module-picker\" x-data=\"picker()\" x-show=\"open\" x-on:picker:open.window=\"open = true; $nextTick(() => $refs.input.focus())\" x-on:keydown.escape.window=\"open = false\" x-on:click.self=\"open = false\" x-cloak><div class=\"module-picker-card\" role=\"dialog\" aria-label=\"Switch module\"><div class=\"module-picker-search\"><span class=\"prompt\" aria-hidden=\"true\">›</span> <input type=\"search\" class=\"module-picker-input\" x-ref=\"input\" x-model=\"query\" placeholder=\"Switch module — start typing to filter…\" autocomplete=\"off\" aria-label=\"Filter modules\"> <span class=\"kbd\" aria-hidden=\"true\">esc</span></div><ul class=\"module-picker-list\" role=\"listbox\"><template x-for=\"(m, idx) in visible\" x-bind:key=\"m.name\"><li class=\"module-picker-item\" role=\"option\" x-bind:data-active=\"idx === active\"><a x-bind:href=\"'/m/' + encodeURIComponent(m.name)\" x-on:mouseenter=\"active = idx\"><code class=\"module-picker-name\" x-text=\"m.name\"></code> <span class=\"module-picker-oid\" x-show=\"m.oid\" x-text=\"m.oid\"></span></a></li></template><li class=\"module-picker-empty\" x-show=\"filtered.length === 0\"><span class=\"module-picker-empty-title\">No modules match</span> <span class=\"module-picker-empty-hint\" x-text=\"'Tried: ' + query\"></span></li></ul><div class=\"module-picker-footer\" x-show=\"hiddenCount > 0\"><span class=\"module-picker-more\" x-text=\"'+ ' + hiddenCount + ' more — keep typing to narrow'\"></span></div></div><!-- picker.js reads the module list from this data attribute on\n\t\tinit (mirroring how walk.templ ships WalkDataJSON). A\n\t\t<script type=\"application/json\"> block cannot carry a templ\n\t\texpression: templ treats script content as raw text, so the\n\t\tcomponent call was emitted as literal source and the picker\n\t\tparsed garbage — rendering \"No modules match\" forever. --><div id=\"module-picker-data\" data-modules=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(PickerModulesJSON(modules))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/module_picker.templ`, Line: 68, Col: 72}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hidden></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
